# Kustomization file
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-fastapi

resources:
  - service.yaml
  - deployment.yaml
  - pdb.yaml

generatorOptions:
  disableNameSuffixHash: true
