# Adds a 2nd label "instance: prod" to the existing "app: ..." label
# allowing multiple instances to be deployed in the same namespace.
- op: add
  path: /metadata/labels/environment
  value: prod

# Copies from above
- op: copy
  path: /spec/selector/matchLabels/environment
  from: /metadata/labels/environment

- op: copy
  path: /spec/template/metadata/labels/environment
  from: /metadata/labels/environment
